/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ESPACE_ADMINISTRATEUR (void);
GtkWidget* create_connexion (void);
GtkWidget* create_Gestion_des_clients (void);
GtkWidget* create_Editer_les_coordonn__es_du_client (void);
GtkWidget* create_CONSULTER_COMPTE_CLIENT (void);
GtkWidget* create_Gestion_des_employ__es (void);
GtkWidget* create_AJOUTER_UN_EMPLOY__ (void);
GtkWidget* create_EDITER_COMPTE_D_EMPLOY__ (void);
GtkWidget* create_Menu_Reclamation (void);
GtkWidget* create_Reclamation_de_la_part__clients_ (void);
GtkWidget* create_Reclamation_de_la_part__employ__es_ (void);
GtkWidget* create_Menu_statistiques (void);
