/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ESPACE_ADMINISTRATEUR (void)
{
  GtkWidget *ESPACE_ADMINISTRATEUR;
  GtkWidget *fixed1;
  GtkWidget *image20;
  GtkWidget *se_connecter;
  GtkWidget *s_inscrire;
  GtkWidget *locationsde_voiture;
  GtkWidget *h__bergements;
  GtkWidget *vols;

  ESPACE_ADMINISTRATEUR = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ESPACE_ADMINISTRATEUR, 0, -1);
  gtk_window_set_title (GTK_WINDOW (ESPACE_ADMINISTRATEUR), _("ESPACE ADMINISTRATEUR"));
  gtk_window_set_position (GTK_WINDOW (ESPACE_ADMINISTRATEUR), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (ESPACE_ADMINISTRATEUR), GDK_WINDOW_TYPE_HINT_DESKTOP);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ESPACE_ADMINISTRATEUR), fixed1);

  image20 = create_pixmap (ESPACE_ADMINISTRATEUR, "interface generale.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed1), image20, 0, 0);
  gtk_widget_set_size_request (image20, 808, 464);

  se_connecter = gtk_button_new_with_mnemonic (_("d\303\251connexion"));
  gtk_widget_show (se_connecter);
  gtk_fixed_put (GTK_FIXED (fixed1), se_connecter, 16, 392);
  gtk_widget_set_size_request (se_connecter, 152, 40);

  s_inscrire = gtk_button_new_with_mnemonic (_("Gestion des clients"));
  gtk_widget_show (s_inscrire);
  gtk_fixed_put (GTK_FIXED (fixed1), s_inscrire, 288, 144);
  gtk_widget_set_size_request (s_inscrire, 232, 48);

  locationsde_voiture = gtk_button_new_with_mnemonic (_("Gestion des employ\303\251s"));
  gtk_widget_show (locationsde_voiture);
  gtk_fixed_put (GTK_FIXED (fixed1), locationsde_voiture, 288, 208);
  gtk_widget_set_size_request (locationsde_voiture, 232, 48);

  h__bergements = gtk_button_new_with_mnemonic (_("Gestion des r\303\251clamations "));
  gtk_widget_show (h__bergements);
  gtk_fixed_put (GTK_FIXED (fixed1), h__bergements, 288, 272);
  gtk_widget_set_size_request (h__bergements, 232, 48);

  vols = gtk_button_new_with_mnemonic (_("Gestion des statistiques"));
  gtk_widget_show (vols);
  gtk_fixed_put (GTK_FIXED (fixed1), vols, 288, 336);
  gtk_widget_set_size_request (vols, 232, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ESPACE_ADMINISTRATEUR, ESPACE_ADMINISTRATEUR, "ESPACE_ADMINISTRATEUR");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, image20, "image20");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, se_connecter, "se_connecter");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, s_inscrire, "s_inscrire");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, locationsde_voiture, "locationsde_voiture");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, h__bergements, "h__bergements");
  GLADE_HOOKUP_OBJECT (ESPACE_ADMINISTRATEUR, vols, "vols");

  return ESPACE_ADMINISTRATEUR;
}

GtkWidget*
create_connexion (void)
{
  GtkWidget *connexion;
  GtkWidget *fixed2;
  GtkWidget *ID;
  GtkWidget *entry2;
  GtkWidget *image2;
  GtkWidget *MDP;
  GtkWidget *identifiant;
  GtkWidget *connexin;

  connexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion), _("connexion"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (connexion), fixed2);

  ID = gtk_entry_new ();
  gtk_widget_show (ID);
  gtk_fixed_put (GTK_FIXED (fixed2), ID, 296, 168);
  gtk_widget_set_size_request (ID, 312, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (ID), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 296, 240);
  gtk_widget_set_size_request (entry2, 312, 32);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  image2 = create_pixmap (connexion, "interface generale.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed2), image2, 0, 0);
  gtk_widget_set_size_request (image2, 808, 464);

  MDP = gtk_label_new (_("mot de passe"));
  gtk_widget_show (MDP);
  gtk_fixed_put (GTK_FIXED (fixed2), MDP, 176, 240);
  gtk_widget_set_size_request (MDP, 120, 32);

  identifiant = gtk_label_new (_("ID/mail"));
  gtk_widget_show (identifiant);
  gtk_fixed_put (GTK_FIXED (fixed2), identifiant, 128, 168);
  gtk_widget_set_size_request (identifiant, 168, 33);
  gtk_label_set_width_chars (GTK_LABEL (identifiant), 9);

  connexin = gtk_button_new_with_mnemonic (_("connexion"));
  gtk_widget_show (connexin);
  gtk_fixed_put (GTK_FIXED (fixed2), connexin, 360, 304);
  gtk_widget_set_size_request (connexin, 216, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (connexion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (connexion, ID, "ID");
  GLADE_HOOKUP_OBJECT (connexion, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (connexion, image2, "image2");
  GLADE_HOOKUP_OBJECT (connexion, MDP, "MDP");
  GLADE_HOOKUP_OBJECT (connexion, identifiant, "identifiant");
  GLADE_HOOKUP_OBJECT (connexion, connexin, "connexin");

  return connexion;
}

GtkWidget*
create_Gestion_des_clients (void)
{
  GtkWidget *Gestion_des_clients;
  GtkWidget *fixed15;
  GtkWidget *entry54;
  GtkWidget *textview4;
  GtkWidget *image21;
  GtkWidget *button11;
  GtkWidget *alignment5;
  GtkWidget *hbox17;
  GtkWidget *image22;
  GtkWidget *label92;
  GtkWidget *button12;
  GtkWidget *button13;

  Gestion_des_clients = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_clients), _("Gestion des clients"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (Gestion_des_clients), fixed15);

  entry54 = gtk_entry_new ();
  gtk_widget_show (entry54);
  gtk_fixed_put (GTK_FIXED (fixed15), entry54, 352, 96);
  gtk_widget_set_size_request (entry54, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry54), 8226);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_fixed_put (GTK_FIXED (fixed15), textview4, 192, 152);
  gtk_widget_set_size_request (textview4, 440, 210);

  image21 = create_pixmap (Gestion_des_clients, "interface generale.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed15), image21, 0, 0);
  gtk_widget_set_size_request (image21, 808, 464);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed15), button11, 504, 96);
  gtk_widget_set_size_request (button11, 128, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button11), alignment5);
  gtk_widget_set_size_request (alignment5, 79, -1);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox17);

  image22 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox17), image22, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox17), label92, FALSE, FALSE, 0);

  button12 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed15), button12, 200, 392);
  gtk_widget_set_size_request (button12, 176, 32);

  button13 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed15), button13, 440, 392);
  gtk_widget_set_size_request (button13, 176, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_clients, Gestion_des_clients, "Gestion_des_clients");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, entry54, "entry54");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, textview4, "textview4");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, image21, "image21");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, button11, "button11");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, image22, "image22");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, label92, "label92");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, button12, "button12");
  GLADE_HOOKUP_OBJECT (Gestion_des_clients, button13, "button13");

  return Gestion_des_clients;
}

GtkWidget*
create_Editer_les_coordonn__es_du_client (void)
{
  GtkWidget *Editer_les_coordonn__es_du_client;
  GtkWidget *fixed16;
  GtkWidget *entry55;
  GtkWidget *entry56;
  GtkWidget *entry57;
  GtkWidget *entry58;
  GtkWidget *entry59;
  GtkWidget *entry60;
  GtkWidget *entry61;
  GtkWidget *image23;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *hseparator1;
  GtkWidget *label99;
  GtkWidget *label101;
  GtkWidget *label100;
  GtkWidget *label97;
  GtkWidget *label96;
  GtkWidget *label103;
  GtkWidget *label98;
  GtkWidget *label102;
  GtkWidget *button14;

  Editer_les_coordonn__es_du_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Editer_les_coordonn__es_du_client), _("Editer les coordonn\303\251es du client "));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (Editer_les_coordonn__es_du_client), fixed16);

  entry55 = gtk_entry_new ();
  gtk_widget_show (entry55);
  gtk_fixed_put (GTK_FIXED (fixed16), entry55, 312, 64);
  gtk_widget_set_size_request (entry55, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry55), 8226);

  entry56 = gtk_entry_new ();
  gtk_widget_show (entry56);
  gtk_fixed_put (GTK_FIXED (fixed16), entry56, 312, 96);
  gtk_widget_set_size_request (entry56, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry56), 8226);

  entry57 = gtk_entry_new ();
  gtk_widget_show (entry57);
  gtk_fixed_put (GTK_FIXED (fixed16), entry57, 312, 136);
  gtk_widget_set_size_request (entry57, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry57), 8226);

  entry58 = gtk_entry_new ();
  gtk_widget_show (entry58);
  gtk_fixed_put (GTK_FIXED (fixed16), entry58, 312, 184);
  gtk_widget_set_size_request (entry58, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry58), 8226);

  entry59 = gtk_entry_new ();
  gtk_widget_show (entry59);
  gtk_fixed_put (GTK_FIXED (fixed16), entry59, 312, 232);
  gtk_widget_set_size_request (entry59, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry59), 8226);

  entry60 = gtk_entry_new ();
  gtk_widget_show (entry60);
  gtk_fixed_put (GTK_FIXED (fixed16), entry60, 312, 272);
  gtk_widget_set_size_request (entry60, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry60), 8226);

  entry61 = gtk_entry_new ();
  gtk_widget_show (entry61);
  gtk_fixed_put (GTK_FIXED (fixed16), entry61, 312, 312);
  gtk_widget_set_size_request (entry61, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry61), 8226);

  image23 = create_pixmap (Editer_les_coordonn__es_du_client, "interface generale.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed16), image23, 0, 0);
  gtk_widget_set_size_request (image23, 808, 464);

  label93 = gtk_label_new (_("Nom"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed16), label93, 256, 64);
  gtk_widget_set_size_request (label93, 48, 24);
  gtk_misc_set_alignment (GTK_MISC (label93), 0, 0.5);

  label94 = gtk_label_new (_("pr\303\251nom"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed16), label94, 240, 96);
  gtk_widget_set_size_request (label94, 88, 32);

  label95 = gtk_label_new (_("CIN"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed16), label95, 232, 136);
  gtk_widget_set_size_request (label95, 72, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed16), hseparator1, 208, 168);
  gtk_widget_set_size_request (hseparator1, 336, 16);

  label99 = gtk_label_new (_("*"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed16), label99, 472, 72);
  gtk_widget_set_size_request (label99, 24, 16);

  label101 = gtk_label_new (_("*"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed16), label101, 472, 104);
  gtk_widget_set_size_request (label101, 24, 16);

  label100 = gtk_label_new (_("*"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed16), label100, 472, 144);
  gtk_widget_set_size_request (label100, 24, 16);

  label97 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed16), label97, 224, 232);
  gtk_widget_set_size_request (label97, 96, 24);

  label96 = gtk_label_new (_("Ville"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed16), label96, 248, 192);
  gtk_widget_set_size_request (label96, 49, 17);

  label103 = gtk_label_new (_("Tel"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed16), label103, 248, 280);
  gtk_widget_set_size_request (label103, 57, 17);

  label98 = gtk_label_new (_("Email"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed16), label98, 240, 312);
  gtk_widget_set_size_request (label98, 72, 24);

  label102 = gtk_label_new (_("(*) : vous ne peut pas modifier \303\247a"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed16), label102, 232, 344);
  gtk_widget_set_size_request (label102, 280, 16);

  button14 = gtk_button_new_with_mnemonic (_("Valider modification"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed16), button14, 288, 384);
  gtk_widget_set_size_request (button14, 192, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Editer_les_coordonn__es_du_client, Editer_les_coordonn__es_du_client, "Editer_les_coordonn__es_du_client");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry55, "entry55");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry56, "entry56");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry57, "entry57");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry58, "entry58");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry59, "entry59");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry60, "entry60");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, entry61, "entry61");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, image23, "image23");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label93, "label93");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label94, "label94");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label95, "label95");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label99, "label99");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label101, "label101");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label100, "label100");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label97, "label97");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label96, "label96");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label103, "label103");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label98, "label98");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, label102, "label102");
  GLADE_HOOKUP_OBJECT (Editer_les_coordonn__es_du_client, button14, "button14");

  return Editer_les_coordonn__es_du_client;
}

GtkWidget*
create_CONSULTER_COMPTE_CLIENT (void)
{
  GtkWidget *CONSULTER_COMPTE_CLIENT;
  GtkWidget *fixed18;
  GtkWidget *image25;
  GtkWidget *label126;
  GtkWidget *label127;
  GtkWidget *label125;
  GtkWidget *button16;
  GtkWidget *button17;

  CONSULTER_COMPTE_CLIENT = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (CONSULTER_COMPTE_CLIENT), _("CONSULTER COMPTE CLIENT"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (CONSULTER_COMPTE_CLIENT), fixed18);

  image25 = create_pixmap (CONSULTER_COMPTE_CLIENT, "interface generale.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed18), image25, 0, 0);
  gtk_widget_set_size_request (image25, 544, 360);

  label126 = gtk_label_new (_("P:"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed18), label126, 200, 32);
  gtk_widget_set_size_request (label126, 168, 33);

  label127 = gtk_label_new (_("ID:"));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed18), label127, 392, 32);
  gtk_widget_set_size_request (label127, 152, 32);

  label125 = gtk_label_new (_("N:"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed18), label125, 16, 32);
  gtk_widget_set_size_request (label125, 176, 32);

  button16 = gtk_button_new_with_mnemonic (_("Reclamation"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed18), button16, 144, 112);
  gtk_widget_set_size_request (button16, 296, 56);

  button17 = gtk_button_new_with_mnemonic (_("Historique"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed18), button17, 144, 192);
  gtk_widget_set_size_request (button17, 296, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (CONSULTER_COMPTE_CLIENT, CONSULTER_COMPTE_CLIENT, "CONSULTER_COMPTE_CLIENT");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, image25, "image25");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, label126, "label126");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, label127, "label127");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, label125, "label125");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, button16, "button16");
  GLADE_HOOKUP_OBJECT (CONSULTER_COMPTE_CLIENT, button17, "button17");

  return CONSULTER_COMPTE_CLIENT;
}

GtkWidget*
create_Gestion_des_employ__es (void)
{
  GtkWidget *Gestion_des_employ__es;
  GtkWidget *fixed19;
  GtkWidget *entry95;
  GtkWidget *textview5;
  GtkWidget *image26;
  GtkWidget *button18;
  GtkWidget *alignment6;
  GtkWidget *hbox18;
  GtkWidget *image27;
  GtkWidget *label160;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *button21;

  Gestion_des_employ__es = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_employ__es), _("Gestion des employ\303\251es"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (Gestion_des_employ__es), fixed19);

  entry95 = gtk_entry_new ();
  gtk_widget_show (entry95);
  gtk_fixed_put (GTK_FIXED (fixed19), entry95, 352, 96);
  gtk_widget_set_size_request (entry95, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry95), 8226);

  textview5 = gtk_text_view_new ();
  gtk_widget_show (textview5);
  gtk_fixed_put (GTK_FIXED (fixed19), textview5, 192, 152);
  gtk_widget_set_size_request (textview5, 440, 210);

  image26 = create_pixmap (Gestion_des_employ__es, "interface generale.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed19), image26, 0, 0);
  gtk_widget_set_size_request (image26, 808, 464);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed19), button18, 504, 96);
  gtk_widget_set_size_request (button18, 128, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button18), alignment6);
  gtk_widget_set_size_request (alignment6, 79, -1);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox18);

  image27 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox18), image27, FALSE, FALSE, 0);

  label160 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label160);
  gtk_box_pack_start (GTK_BOX (hbox18), label160, FALSE, FALSE, 0);

  button19 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed19), button19, 120, 376);
  gtk_widget_set_size_request (button19, 176, 32);

  button20 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed19), button20, 304, 376);
  gtk_widget_set_size_request (button20, 176, 32);

  button21 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed19), button21, 488, 376);
  gtk_widget_set_size_request (button21, 168, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_employ__es, Gestion_des_employ__es, "Gestion_des_employ__es");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, entry95, "entry95");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, textview5, "textview5");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, image26, "image26");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, button18, "button18");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, image27, "image27");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, label160, "label160");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, button19, "button19");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, button20, "button20");
  GLADE_HOOKUP_OBJECT (Gestion_des_employ__es, button21, "button21");

  return Gestion_des_employ__es;
}

GtkWidget*
create_AJOUTER_UN_EMPLOY__ (void)
{
  GtkWidget *AJOUTER_UN_EMPLOY__;
  GtkWidget *fixed20;
  GtkWidget *entry96;
  GtkWidget *entry97;
  GtkWidget *entry98;
  GtkWidget *entry99;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry102;
  GtkWidget *image28;
  GtkWidget *label161;
  GtkWidget *label162;
  GtkWidget *hseparator3;
  GtkWidget *label167;
  GtkWidget *label170;
  GtkWidget *label172;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *label168;
  GtkWidget *label163;

  AJOUTER_UN_EMPLOY__ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AJOUTER_UN_EMPLOY__), _("AJOUTER UN EMPLOY\303\211"));

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (AJOUTER_UN_EMPLOY__), fixed20);

  entry96 = gtk_entry_new ();
  gtk_widget_show (entry96);
  gtk_fixed_put (GTK_FIXED (fixed20), entry96, 312, 64);
  gtk_widget_set_size_request (entry96, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry96), 8226);

  entry97 = gtk_entry_new ();
  gtk_widget_show (entry97);
  gtk_fixed_put (GTK_FIXED (fixed20), entry97, 312, 96);
  gtk_widget_set_size_request (entry97, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry97), 8226);

  entry98 = gtk_entry_new ();
  gtk_widget_show (entry98);
  gtk_fixed_put (GTK_FIXED (fixed20), entry98, 312, 136);
  gtk_widget_set_size_request (entry98, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry98), 8226);

  entry99 = gtk_entry_new ();
  gtk_widget_show (entry99);
  gtk_fixed_put (GTK_FIXED (fixed20), entry99, 312, 184);
  gtk_widget_set_size_request (entry99, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry99), 8226);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed20), entry100, 312, 232);
  gtk_widget_set_size_request (entry100, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed20), entry101, 312, 272);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry102 = gtk_entry_new ();
  gtk_widget_show (entry102);
  gtk_fixed_put (GTK_FIXED (fixed20), entry102, 312, 312);
  gtk_widget_set_size_request (entry102, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102), 8226);

  image28 = create_pixmap (AJOUTER_UN_EMPLOY__, "interface generale.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed20), image28, 0, 0);
  gtk_widget_set_size_request (image28, 808, 464);

  label161 = gtk_label_new (_("Nom"));
  gtk_widget_show (label161);
  gtk_fixed_put (GTK_FIXED (fixed20), label161, 256, 64);
  gtk_widget_set_size_request (label161, 48, 24);
  gtk_misc_set_alignment (GTK_MISC (label161), 0, 0.5);

  label162 = gtk_label_new (_("pr\303\251nom"));
  gtk_widget_show (label162);
  gtk_fixed_put (GTK_FIXED (fixed20), label162, 240, 96);
  gtk_widget_set_size_request (label162, 88, 32);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed20), hseparator3, 208, 168);
  gtk_widget_set_size_request (hseparator3, 336, 16);

  label167 = gtk_label_new (_("Tel"));
  gtk_widget_show (label167);
  gtk_fixed_put (GTK_FIXED (fixed20), label167, 224, 232);
  gtk_widget_set_size_request (label167, 96, 24);

  label170 = gtk_label_new (_("SP"));
  gtk_widget_show (label170);
  gtk_fixed_put (GTK_FIXED (fixed20), label170, 240, 272);
  gtk_widget_set_size_request (label170, 72, 24);

  label172 = gtk_label_new (_("Autre"));
  gtk_widget_show (label172);
  gtk_fixed_put (GTK_FIXED (fixed20), label172, 248, 312);
  gtk_widget_set_size_request (label172, 57, 17);

  button22 = gtk_button_new_with_mnemonic (_("Valider "));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed20), button22, 168, 376);
  gtk_widget_set_size_request (button22, 192, 40);

  button23 = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed20), button23, 384, 376);
  gtk_widget_set_size_request (button23, 200, 40);

  label168 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label168);
  gtk_fixed_put (GTK_FIXED (fixed20), label168, 208, 184);
  gtk_widget_set_size_request (label168, 105, 25);

  label163 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label163);
  gtk_fixed_put (GTK_FIXED (fixed20), label163, 232, 136);
  gtk_widget_set_size_request (label163, 72, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AJOUTER_UN_EMPLOY__, AJOUTER_UN_EMPLOY__, "AJOUTER_UN_EMPLOY__");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry96, "entry96");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry97, "entry97");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry98, "entry98");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry99, "entry99");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, entry102, "entry102");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, image28, "image28");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label161, "label161");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label162, "label162");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label167, "label167");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label170, "label170");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label172, "label172");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, button22, "button22");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, button23, "button23");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label168, "label168");
  GLADE_HOOKUP_OBJECT (AJOUTER_UN_EMPLOY__, label163, "label163");

  return AJOUTER_UN_EMPLOY__;
}

GtkWidget*
create_EDITER_COMPTE_D_EMPLOY__ (void)
{
  GtkWidget *EDITER_COMPTE_D_EMPLOY__;
  GtkWidget *fixed21;
  GtkWidget *entry103;
  GtkWidget *entry104;
  GtkWidget *entry105;
  GtkWidget *entry106;
  GtkWidget *entry107;
  GtkWidget *entry108;
  GtkWidget *entry109;
  GtkWidget *hseparator4;
  GtkWidget *image29;
  GtkWidget *label176;
  GtkWidget *label177;
  GtkWidget *label173;
  GtkWidget *label174;
  GtkWidget *label179;
  GtkWidget *label175;
  GtkWidget *label181;
  GtkWidget *label182;
  GtkWidget *label180;
  GtkWidget *label183;
  GtkWidget *button24;
  GtkWidget *button25;

  EDITER_COMPTE_D_EMPLOY__ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (EDITER_COMPTE_D_EMPLOY__), _("EDITER COMPTE D'EMPLOY\303\211"));

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (EDITER_COMPTE_D_EMPLOY__), fixed21);

  entry103 = gtk_entry_new ();
  gtk_widget_show (entry103);
  gtk_fixed_put (GTK_FIXED (fixed21), entry103, 312, 64);
  gtk_widget_set_size_request (entry103, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry103), 8226);

  entry104 = gtk_entry_new ();
  gtk_widget_show (entry104);
  gtk_fixed_put (GTK_FIXED (fixed21), entry104, 312, 96);
  gtk_widget_set_size_request (entry104, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry104), 8226);

  entry105 = gtk_entry_new ();
  gtk_widget_show (entry105);
  gtk_fixed_put (GTK_FIXED (fixed21), entry105, 312, 136);
  gtk_widget_set_size_request (entry105, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry105), 8226);

  entry106 = gtk_entry_new ();
  gtk_widget_show (entry106);
  gtk_fixed_put (GTK_FIXED (fixed21), entry106, 312, 184);
  gtk_widget_set_size_request (entry106, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry106), 8226);

  entry107 = gtk_entry_new ();
  gtk_widget_show (entry107);
  gtk_fixed_put (GTK_FIXED (fixed21), entry107, 312, 232);
  gtk_widget_set_size_request (entry107, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry107), 8226);

  entry108 = gtk_entry_new ();
  gtk_widget_show (entry108);
  gtk_fixed_put (GTK_FIXED (fixed21), entry108, 312, 272);
  gtk_widget_set_size_request (entry108, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry108), 8226);

  entry109 = gtk_entry_new ();
  gtk_widget_show (entry109);
  gtk_fixed_put (GTK_FIXED (fixed21), entry109, 312, 312);
  gtk_widget_set_size_request (entry109, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry109), 8226);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed21), hseparator4, 208, 168);
  gtk_widget_set_size_request (hseparator4, 336, 16);

  image29 = create_pixmap (EDITER_COMPTE_D_EMPLOY__, "interface generale.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed21), image29, 0, 0);
  gtk_widget_set_size_request (image29, 800, 464);

  label176 = gtk_label_new (_("*"));
  gtk_widget_show (label176);
  gtk_fixed_put (GTK_FIXED (fixed21), label176, 480, 64);
  gtk_widget_set_size_request (label176, 24, 16);

  label177 = gtk_label_new (_("*"));
  gtk_widget_show (label177);
  gtk_fixed_put (GTK_FIXED (fixed21), label177, 480, 104);
  gtk_widget_set_size_request (label177, 24, 16);

  label173 = gtk_label_new (_("Nom"));
  gtk_widget_show (label173);
  gtk_fixed_put (GTK_FIXED (fixed21), label173, 264, 64);
  gtk_widget_set_size_request (label173, 48, 24);
  gtk_misc_set_alignment (GTK_MISC (label173), 0, 0.5);

  label174 = gtk_label_new (_("pr\303\251nom"));
  gtk_widget_show (label174);
  gtk_fixed_put (GTK_FIXED (fixed21), label174, 232, 88);
  gtk_widget_set_size_request (label174, 88, 32);

  label179 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label179);
  gtk_fixed_put (GTK_FIXED (fixed21), label179, 224, 136);
  gtk_widget_set_size_request (label179, 96, 24);

  label175 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label175);
  gtk_fixed_put (GTK_FIXED (fixed21), label175, 200, 184);
  gtk_widget_set_size_request (label175, 120, 24);

  label181 = gtk_label_new (_("Tel"));
  gtk_widget_show (label181);
  gtk_fixed_put (GTK_FIXED (fixed21), label181, 240, 232);
  gtk_widget_set_size_request (label181, 57, 17);

  label182 = gtk_label_new (_("Email"));
  gtk_widget_show (label182);
  gtk_fixed_put (GTK_FIXED (fixed21), label182, 232, 272);
  gtk_widget_set_size_request (label182, 72, 24);

  label180 = gtk_label_new (_("SP"));
  gtk_widget_show (label180);
  gtk_fixed_put (GTK_FIXED (fixed21), label180, 248, 312);
  gtk_widget_set_size_request (label180, 49, 17);

  label183 = gtk_label_new (_("(*) : vous ne peut pas modifier \303\247a"));
  gtk_widget_show (label183);
  gtk_fixed_put (GTK_FIXED (fixed21), label183, 256, 344);
  gtk_widget_set_size_request (label183, 280, 16);

  button24 = gtk_button_new_with_mnemonic (_("Valider modification"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed21), button24, 184, 384);
  gtk_widget_set_size_request (button24, 192, 40);

  button25 = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed21), button25, 432, 384);
  gtk_widget_set_size_request (button25, 80, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (EDITER_COMPTE_D_EMPLOY__, EDITER_COMPTE_D_EMPLOY__, "EDITER_COMPTE_D_EMPLOY__");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry103, "entry103");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry104, "entry104");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry105, "entry105");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry106, "entry106");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry107, "entry107");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry108, "entry108");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, entry109, "entry109");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, image29, "image29");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label176, "label176");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label177, "label177");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label173, "label173");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label174, "label174");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label179, "label179");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label175, "label175");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label181, "label181");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label182, "label182");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label180, "label180");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, label183, "label183");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, button24, "button24");
  GLADE_HOOKUP_OBJECT (EDITER_COMPTE_D_EMPLOY__, button25, "button25");

  return EDITER_COMPTE_D_EMPLOY__;
}

GtkWidget*
create_Menu_Reclamation (void)
{
  GtkWidget *Menu_Reclamation;
  GtkWidget *fixed22;
  GtkWidget *image30;
  GtkWidget *button26;
  GtkWidget *button27;

  Menu_Reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Menu_Reclamation), _("Menu Reclamation"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (Menu_Reclamation), fixed22);

  image30 = create_pixmap (Menu_Reclamation, "interface generale.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed22), image30, 0, 0);
  gtk_widget_set_size_request (image30, 544, 360);

  button26 = gtk_button_new_with_mnemonic (_("Reclamation de la part \"employ\303\251es\""));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed22), button26, 144, 112);
  gtk_widget_set_size_request (button26, 296, 56);

  button27 = gtk_button_new_with_mnemonic (_("Reclamation de la part \"clients\""));
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed22), button27, 144, 192);
  gtk_widget_set_size_request (button27, 296, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_Reclamation, Menu_Reclamation, "Menu_Reclamation");
  GLADE_HOOKUP_OBJECT (Menu_Reclamation, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (Menu_Reclamation, image30, "image30");
  GLADE_HOOKUP_OBJECT (Menu_Reclamation, button26, "button26");
  GLADE_HOOKUP_OBJECT (Menu_Reclamation, button27, "button27");

  return Menu_Reclamation;
}

GtkWidget*
create_Reclamation_de_la_part__clients_ (void)
{
  GtkWidget *Reclamation_de_la_part__clients_;
  GtkWidget *fixed23;
  GtkWidget *image31;
  GtkWidget *button28;
  GtkWidget *button29;

  Reclamation_de_la_part__clients_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Reclamation_de_la_part__clients_), _("Reclamation de la part \"clients\""));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (Reclamation_de_la_part__clients_), fixed23);

  image31 = create_pixmap (Reclamation_de_la_part__clients_, "interface generale.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed23), image31, 0, 0);
  gtk_widget_set_size_request (image31, 544, 360);

  button28 = gtk_button_new_with_mnemonic (_("Prestations"));
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed23), button28, 144, 112);
  gtk_widget_set_size_request (button28, 296, 56);

  button29 = gtk_button_new_with_mnemonic (_("Services internes"));
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed23), button29, 144, 192);
  gtk_widget_set_size_request (button29, 296, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reclamation_de_la_part__clients_, Reclamation_de_la_part__clients_, "Reclamation_de_la_part__clients_");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__clients_, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__clients_, image31, "image31");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__clients_, button28, "button28");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__clients_, button29, "button29");

  return Reclamation_de_la_part__clients_;
}

GtkWidget*
create_Reclamation_de_la_part__employ__es_ (void)
{
  GtkWidget *Reclamation_de_la_part__employ__es_;
  GtkWidget *fixed24;
  GtkWidget *image32;
  GtkWidget *button30;
  GtkWidget *button31;

  Reclamation_de_la_part__employ__es_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Reclamation_de_la_part__employ__es_), _("Reclamation de la part \"employ\303\251es\""));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (Reclamation_de_la_part__employ__es_), fixed24);

  image32 = create_pixmap (Reclamation_de_la_part__employ__es_, "interface generale.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed24), image32, 0, 0);
  gtk_widget_set_size_request (image32, 544, 360);

  button30 = gtk_button_new_with_mnemonic (_("Systeme interne"));
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed24), button30, 144, 112);
  gtk_widget_set_size_request (button30, 296, 56);

  button31 = gtk_button_new_with_mnemonic (_("Fournisseurs"));
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed24), button31, 144, 192);
  gtk_widget_set_size_request (button31, 296, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reclamation_de_la_part__employ__es_, Reclamation_de_la_part__employ__es_, "Reclamation_de_la_part__employ__es_");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__employ__es_, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__employ__es_, image32, "image32");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__employ__es_, button30, "button30");
  GLADE_HOOKUP_OBJECT (Reclamation_de_la_part__employ__es_, button31, "button31");

  return Reclamation_de_la_part__employ__es_;
}

GtkWidget*
create_Menu_statistiques (void)
{
  GtkWidget *Menu_statistiques;
  GtkWidget *fixed25;
  GtkWidget *image33;
  GtkWidget *button32;
  GtkWidget *button33;
  GtkWidget *button34;

  Menu_statistiques = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Menu_statistiques), _("Menu statistiques"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Menu_statistiques), fixed25);

  image33 = create_pixmap (Menu_statistiques, "interface generale.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed25), image33, 0, 0);
  gtk_widget_set_size_request (image33, 544, 360);

  button32 = gtk_button_new_with_mnemonic (_("Reclamation"));
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed25), button32, 144, 32);
  gtk_widget_set_size_request (button32, 296, 56);

  button33 = gtk_button_new_with_mnemonic (_("Historique"));
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed25), button33, 144, 120);
  gtk_widget_set_size_request (button33, 296, 56);

  button34 = gtk_button_new_with_mnemonic (_("Notes \360\237\217\205\360\237\217\205\360\237\217\205"));
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed25), button34, 144, 216);
  gtk_widget_set_size_request (button34, 296, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_statistiques, Menu_statistiques, "Menu_statistiques");
  GLADE_HOOKUP_OBJECT (Menu_statistiques, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Menu_statistiques, image33, "image33");
  GLADE_HOOKUP_OBJECT (Menu_statistiques, button32, "button32");
  GLADE_HOOKUP_OBJECT (Menu_statistiques, button33, "button33");
  GLADE_HOOKUP_OBJECT (Menu_statistiques, button34, "button34");

  return Menu_statistiques;
}

