/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ESPACE_ADMINISTRATEUR;
  GtkWidget *connexion;
  GtkWidget *Gestion_des_clients;
  GtkWidget *Editer_les_coordonn__es_du_client;
  GtkWidget *CONSULTER_COMPTE_CLIENT;
  GtkWidget *Gestion_des_employ__es;
  GtkWidget *AJOUTER_UN_EMPLOY__;
  GtkWidget *EDITER_COMPTE_D_EMPLOY__;
  GtkWidget *Menu_Reclamation;
  GtkWidget *Reclamation_de_la_part__clients_;
  GtkWidget *Reclamation_de_la_part__employ__es_;
  GtkWidget *Menu_statistiques;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ESPACE_ADMINISTRATEUR = create_ESPACE_ADMINISTRATEUR ();
  gtk_widget_show (ESPACE_ADMINISTRATEUR);
  connexion = create_connexion ();
  gtk_widget_show (connexion);
  Gestion_des_clients = create_Gestion_des_clients ();
  gtk_widget_show (Gestion_des_clients);
  Editer_les_coordonn__es_du_client = create_Editer_les_coordonn__es_du_client ();
  gtk_widget_show (Editer_les_coordonn__es_du_client);
  CONSULTER_COMPTE_CLIENT = create_CONSULTER_COMPTE_CLIENT ();
  gtk_widget_show (CONSULTER_COMPTE_CLIENT);
  Gestion_des_employ__es = create_Gestion_des_employ__es ();
  gtk_widget_show (Gestion_des_employ__es);
  AJOUTER_UN_EMPLOY__ = create_AJOUTER_UN_EMPLOY__ ();
  gtk_widget_show (AJOUTER_UN_EMPLOY__);
  EDITER_COMPTE_D_EMPLOY__ = create_EDITER_COMPTE_D_EMPLOY__ ();
  gtk_widget_show (EDITER_COMPTE_D_EMPLOY__);
  Menu_Reclamation = create_Menu_Reclamation ();
  gtk_widget_show (Menu_Reclamation);
  Reclamation_de_la_part__clients_ = create_Reclamation_de_la_part__clients_ ();
  gtk_widget_show (Reclamation_de_la_part__clients_);
  Reclamation_de_la_part__employ__es_ = create_Reclamation_de_la_part__employ__es_ ();
  gtk_widget_show (Reclamation_de_la_part__employ__es_);
  Menu_statistiques = create_Menu_statistiques ();
  gtk_widget_show (Menu_statistiques);

  gtk_main ();
  return 0;
}

